### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by xxzozaxx** [juanfra684/racket-musl#1]
![2018-03-18-184720_1600x900_scrot](https://user-images.githubusercontent.com/20381921/37569650-61e843b2-2add-11e8-87e8-bc1c097a9d12.png)
![2018-03-18-184733_1600x900_scrot](https://user-images.githubusercontent.com/20381921/37569651-621f5712-2add-11e8-84ca-0c5e6f27d3cb.png)
________________
OS : Void Linux musl
just compiling "In-place build"

**Comment by juanfra684** [comment]
Hi, this is an old repo used only for some tests. Recently, Alpine added
a package which works fine with musl. Use their work instead of this
repo.

https://github.com/racket/racket/issues/1638

Cheers.

**Comment by xxzozaxx** [comment]
solved, one of Void linux community shift it from alpine to void repo
